name: Multiarch build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

env:
  IMAGE_NAME: musicxml-player
  IMAGE_TAG: latest
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: tli551

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}

      - name: build and push player images
        run: |
          docker buildx build --push \
            --tag ${{env.IMAGE_NAMESPACE }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            --platform linux/amd64,linux/arm64 .